POST http://localhost:8000/auth/user/register
Content-Type: application/json

{
    "name": "abcannan",
    "email": "abc@fakemail.com",
    "password": "babumon"
}

###
POST http://localhost:8000/auth/user/login
Content-Type: application/json

{
    "email": "abc@fakemail.com",
    "password": "babumon"
}

###
GET http://localhost:8000/auth/user/me
